### ISSUE TITLE
Face location is incorrect if gallery browser window is not fullscreen

### ISSUE THREAD

**Issue by lperovskaya** [icpc/gallery#4]

**Comment by lperovskaya** [comment]
I think part of this issue fix led to photos opening not in fullscreen mode. Let's investigate

**Comment by azat-ismagilov** [comment]
Should be fixed in #fa8436f

**Comment by lperovskaya** [comment]
![image](https://github.com/icpc/gallery/assets/2369861/aed335ab-5f4e-404d-9157-1ed79be05d27)
still not perfect

**Comment by lperovskaya** [comment]
http://news.icpc.global/gallery/?album=2018&event=Photo+Tour&photo=40777813034

**Comment by azat-ismagilov** [comment]
@lperovskaya, should be fixed
